### ISSUE TITLE
Can't login with access token

### ISSUE THREAD

**Issue by tycrek** [GeyserMC/MCAuthLib#11]
For some reason when trying to use Access Token instead of password, I get `RequestException: Access Token can not be null or empty`

Here is the error:
![image](https://user-images.githubusercontent.com/29926144/110392940-f99f2080-8026-11eb-9267-84060339ea53.png)

Here is the code setting the access token (hardcoded for now for testing):
![image](https://user-images.githubusercontent.com/29926144/110392985-10de0e00-8027-11eb-84d9-73f3fef1cf9e.png)

**Comment by Steveice10** [comment]
The MCAuthLib you are using does not match what is in the repository. If you check [AuthenticationService](https://github.com/Steveice10/MCAuthLib/blob/master/src/main/java/com/github/steveice10/mc/auth/service/AuthenticationService.java), you will see there is no loginWithToken.
