### ISSUE TITLE
Allow the getting and setting of URLs in the different services.

### ISSUE THREAD

**Issue by burgerindividual** [GeyserMC/MCAuthLib#8]
Currently, all of the services have their URLs set to private static final variables. I initially thought this would be fine and easy to overwrite with reflection. Unfortunately, the variables are inlined at compile time into the methods that use them. Could you add some getters and setters for the URLs in those classes? Specifically the ones in `com.github.steveice10.mc.auth.service`. Thanks!

**Comment by Steveice10** [comment]
Do you need to be able to set all of the URLs, or just the base URLs for the services?

**Comment by Steveice10** [comment]
I've added setters to all services for changing their base URLs. Let me know if this is enough for your use case, and otherwise I can re-open the issue.

**Comment by ggmoritz** [comment]
@Steveice10 Not OP, but it is not possible to change the SessionService's base URL when using MCProtocolLib. Would be nice if you could add this.

**Comment by Steveice10** [comment]
Will open an issue for that on MCProtocolLib itself.
