### ISSUE TITLE
Microsoft Account Authentication

### ISSUE THREAD

**Issue by Camotoy** [GeyserMC/MCAuthLib#9]
As of December 1st, all new Minecraft accounts created are authenticated using Microsoft's services. The process is documented here: https://wiki.vg/Microsoft_Authentication_Scheme

It is unknown if the first step can be done without a browser.

This is something the Geyser team can tackle, but I'm setting this issue up for tracking.

**Comment by Steveice10** [comment]
I haven't familiarized myself with all of the details yet, but given that old accounts are being migrated later, will both auth systems need to be supported until that migration happens?

**Comment by Camotoy** [comment]
Yes. The migration is being rolled out, so we can deprecate the old Yggdrasil stuff, keep it for now, and rip it out once the migration is 100% complete (after a certain point there will be no Yggdrasil accounts).

**Comment by Camotoy** [comment]
For passersby, our work-in-progress branch is located at https://github.com/GeyserMC/MCAuthLib .

**Comment by Steveice10** [comment]
Pull request has been merged, any problems should be reported in new issue tickets.
